version: "3.9"

services:
  db-dev:
    container_name: postgres-fitness
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - back

networks:
  back:
    driver: bridge
